server:
  port: 9999
  servlet:
    context-path: /

spring:
  application:
    name: db-export
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

databaseExport:
  startWeb: false

database:
  jdbc:
    mysql: jdbc:mysql://%s:%s/%s?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    oracle: jdbc:oracle:thin:@//%s:%s/%s
    sqlServer: jdbc:sqlserver://%s:%s;databaseName=%s;encrypt=false
    postgresql: jdbc:postgresql://%s:%s/%s?currentSchema=%s
    clickhouse: jdbc:clickhouse://%s:%s/%s
    sqlite: jdbc:sqlite:%s
    dm: jdbc:dm://%s:%s/%s
    db2: jdbc:db2://%s:%s/%s:currentSchema=%s;
  driver:
    mysql: com.mysql.cj.jdbc.Driver
    oracle: oracle.jdbc.OracleDriver
    sqlServer: com.microsoft.sqlserver.jdbc.SQLServerDriver
    postgresql: org.postgresql.Driver
    clickhouse: com.clickhouse.jdbc.ClickHouseDriver
    sqlite: org.sqlite.JDBC
    dm: dm.jdbc.driver.DmDriver
    db2: com.ibm.db2.jcc.DB2Driver